# Generated by Django 5.1 on 2024-08-31 18:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Used for soft deleting records.",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        help_text="The access token associated with the Item data is being requested for.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        help_text="The item_id value of the Item associated with the returned access_token.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "institution_id",
                    models.TextField(
                        help_text="The Plaid Institution ID associated with the Item."
                    ),
                ),
                (
                    "institution_name",
                    models.TextField(
                        help_text="The Plaid Institution name associated with the Item."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("GOOD", "Good"), ("BAD", "Bad")],
                        help_text="Status of the item. `Good` or `Bad`",
                        max_length=4,
                    ),
                ),
                (
                    "new_accounts_detected",
                    models.BooleanField(
                        default=False,
                        help_text="Set to `True` when Plaid detects a new account for Items created or updated with Account Select v2.",
                    ),
                ),
                (
                    "transactions_cursor",
                    models.TextField(
                        blank=True,
                        help_text="Cursor used for fetching any future transaction updates after the latest update provided in a transaction response.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
